/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShoppingCartSummaryIndexRouteImport } from './routes/shopping-cart-summary/index'
import { Route as CounterIndexRouteImport } from './routes/counter/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingCartSummaryIndexRoute =
  ShoppingCartSummaryIndexRouteImport.update({
    id: '/shopping-cart-summary/',
    path: '/shopping-cart-summary/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CounterIndexRoute = CounterIndexRouteImport.update({
  id: '/counter/',
  path: '/counter/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/counter': typeof CounterIndexRoute
  '/shopping-cart-summary': typeof ShoppingCartSummaryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/counter': typeof CounterIndexRoute
  '/shopping-cart-summary': typeof ShoppingCartSummaryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/counter/': typeof CounterIndexRoute
  '/shopping-cart-summary/': typeof ShoppingCartSummaryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/counter' | '/shopping-cart-summary'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/counter' | '/shopping-cart-summary'
  id: '__root__' | '/' | '/counter/' | '/shopping-cart-summary/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CounterIndexRoute: typeof CounterIndexRoute
  ShoppingCartSummaryIndexRoute: typeof ShoppingCartSummaryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-cart-summary/': {
      id: '/shopping-cart-summary/'
      path: '/shopping-cart-summary'
      fullPath: '/shopping-cart-summary'
      preLoaderRoute: typeof ShoppingCartSummaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counter/': {
      id: '/counter/'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CounterIndexRoute: CounterIndexRoute,
  ShoppingCartSummaryIndexRoute: ShoppingCartSummaryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
