/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as ShoppingCartIndexRouteImport } from './routes/shopping-cart/index'
import { Route as FirebasePostsIndexRouteImport } from './routes/firebase-posts/index'
import { Route as CounterIndexRouteImport } from './routes/counter/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingCartIndexRoute = ShoppingCartIndexRouteImport.update({
  id: '/shopping-cart/',
  path: '/shopping-cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const FirebasePostsIndexRoute = FirebasePostsIndexRouteImport.update({
  id: '/firebase-posts/',
  path: '/firebase-posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterIndexRoute = CounterIndexRouteImport.update({
  id: '/counter/',
  path: '/counter/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/counter': typeof CounterIndexRoute
  '/firebase-posts': typeof FirebasePostsIndexRoute
  '/shopping-cart': typeof ShoppingCartIndexRoute
  '/test': typeof TestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/counter': typeof CounterIndexRoute
  '/firebase-posts': typeof FirebasePostsIndexRoute
  '/shopping-cart': typeof ShoppingCartIndexRoute
  '/test': typeof TestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/counter/': typeof CounterIndexRoute
  '/firebase-posts/': typeof FirebasePostsIndexRoute
  '/shopping-cart/': typeof ShoppingCartIndexRoute
  '/test/': typeof TestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/counter' | '/firebase-posts' | '/shopping-cart' | '/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/counter' | '/firebase-posts' | '/shopping-cart' | '/test'
  id:
    | '__root__'
    | '/'
    | '/counter/'
    | '/firebase-posts/'
    | '/shopping-cart/'
    | '/test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CounterIndexRoute: typeof CounterIndexRoute
  FirebasePostsIndexRoute: typeof FirebasePostsIndexRoute
  ShoppingCartIndexRoute: typeof ShoppingCartIndexRoute
  TestIndexRoute: typeof TestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-cart/': {
      id: '/shopping-cart/'
      path: '/shopping-cart'
      fullPath: '/shopping-cart'
      preLoaderRoute: typeof ShoppingCartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firebase-posts/': {
      id: '/firebase-posts/'
      path: '/firebase-posts'
      fullPath: '/firebase-posts'
      preLoaderRoute: typeof FirebasePostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counter/': {
      id: '/counter/'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CounterIndexRoute: CounterIndexRoute,
  FirebasePostsIndexRoute: FirebasePostsIndexRoute,
  ShoppingCartIndexRoute: ShoppingCartIndexRoute,
  TestIndexRoute: TestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
